# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0003_bunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enname', models.CharField(max_length=140)),
                ('krname', models.CharField(max_length=140)),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='like',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='like',
            name='creator',
        ),
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bunch',
            name='creator',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='bunch',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bunches', to='flowers.Flower'),
        ),
    ]
