# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_auto_20180121_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunch',
            name='bouquet',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='bunches',
            field=models.ManyToManyField(to='flowers.Bunch'),
        ),
    ]
