# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_auto_20180121_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunch',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='bunches',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.Flower'),
        ),
        migrations.DeleteModel(
            name='Bunch',
        ),
    ]
